name: Accept paper
on:
  workflow_dispatch:
    inputs:
      repository_url:
        description: 'URL of the repository containing the paper file'
        required: true
      branch:
        description: 'Git branch where the paper Markdown file is'
        required: false
      issue_id:
        description: 'The issue number of the submission'
        required: true
jobs:
  acceptance-and-publishing:
    runs-on: ubuntu-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      - name: Compile Paper
        id: generate-files
        uses: xuanxu/paper-action@main
        with:
          repository_url: ${{ github.event.inputs.repository_url }}
          branch: ${{ github.event.inputs.branch }}
          issue_id: ${{ github.event.inputs.issue_id }}
          journal: test_journal
      - name: Upload files to papers repo
        id: upload-files
        uses: xuanxu/upload-files-action@main
        with:
          papers_repo: openjournals/joss-papers-testing
          branch_prefix: joss-testing
          issue_id: ${{ github.event.inputs.issue_id }}
          pdf_path: ${{ steps.generate-files.outputs.pdf_path}}
          jats_path: ${{ steps.generate-files.outputs.jats_path}}
          crossref_path: ${{ steps.generate-files.outputs.crossref_path}}
      - name: Create and Merge Pull Request
        id: pull-request
        uses: xuanxu/deposit-pull-request-action@main
        with:
          papers_repo: openjournals/joss-papers-testing
          papers_repo_main_branch: master
          branch_prefix: joss-testing
          issue_id: ${{ github.event.inputs.issue_id }}
          bot_token: ${{ secrets.BOT_TOKEN }}
          mode: deposit
      - name: Deposit with Crossref
        uses: xuanxu/deposit-with-crossref-action@main
        with:
          crossref_filepath: ${{ steps.generate-files.outputs.crossref_path}}
          crossref_username: ${{ secrets.CROSSREF_USERNAME }}
          crossref_password: ${{ secrets.CROSSREF_PASSWORD }}
          crossref_mode: test
      - name: Deposit with JOSS
        uses: xuanxu/deposit-with-openjournals-action@main
        with:
          journal_alias: joss-test
          journal_secret: ${{ secrets.JOSS_SECRET }}
          issue_id: ${{ github.event.inputs.issue_id }}
          paper_path: ${{ steps.generate-files.outputs.paper_file_path}}
      - name: Reply message
        if: ${{ success() }}
        run: |
          gh issue comment ${{ github.event.inputs.issue_id }} --body "🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨\n\n Here's what you must now do:

          0. Check final PDF and Crossref metadata that was deposited :point_right: ${{ steps.pull-request.outputs.pr_url}}
          1. Wait a couple of minutes, then verify that the paper DOI resolves [#{doi}](#{doi})
          2. If everything looks good, then close this review issue.
          3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

          Any issues? Notify your editorial technical team..."
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          GH_REPO: openjournals/joss-reviews-testing
      - name: Error message
        if: ${{ failure() }}
        run: |
          gh issue comment ${{ github.event.inputs.issue_id }} --body ":warning: Couldn't acccept/publish paper. [An error happened](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}?check_suite_focus=true)."
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          GH_REPO: openjournals/joss-reviews-testing
