name: Generate Citation Info
on:
  workflow_dispatch:
    inputs:
      repository_url:
        description: 'URL of the repository containing the paper file'
        required: true
      branch:
        description: 'Git branch where the paper Markdown file is'
        required: false
      issue_id:
        description: 'The issue number of the submission'
        required: true
jobs:
  generate-citation-info:
    name: ${{ format('Citation info for {0}', github.event.inputs.issue_id) }}
    runs-on: ubuntu-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      - name: Compile Paper
        id: generate-files
        uses: xuanxu/paper-action@main
        with:
          repository_url: ${{ github.event.inputs.repository_url }}
          branch: ${{ github.event.inputs.branch }}
          issue_id: ${{ github.event.inputs.issue_id }}
          journal: test_journal
          compile_mode: accepted
      - name: Citation.cff file info
        uses: xuanxu/citation-file-action@main
        with:
          citation_file_path: ${{ steps.generate-files.outputs.citation_file_path}}
          issue_id: ${{ github.event.inputs.issue_id }}
          reviews_repo: openjournals/joss-reviews-testing
          gh_token: ${{ secrets.BOT_TOKEN }}
      - name: Labeling
        if: ${{ success() && github.event.inputs.add_labels != '' }}
        run: gh issue edit ${{ github.event.inputs.issue_id }} --add-label ${{ github.event.inputs.add_labels }}
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          GH_REPO: openjournals/joss-reviews-testing
      - name: Error message
        if: ${{ failure() }}
        run: |
          gh issue comment ${{ github.event.inputs.issue_id }} --body ":warning: Couldn't generate citation info for this paper. [An error happened](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}?check_suite_focus=true). ${{ env.CUSTOM_ERROR }}"
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          GH_REPO: openjournals/joss-reviews-testing
