name: Reviewers matching
on:
  workflow_dispatch:
    inputs:
      repository_url:
        description: 'URL of the repository containing the paper file'
        required: true
      branch:
        description: 'Git branch where the paper Markdown file is'
        required: false
      issue_id:
        description: 'The issue number of the submission'
        required: true
jobs:
  reviewer-matching:
    name: Reviewer matching
    runs-on: ubuntu-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      - name: Generate PDF
        id: generate-files
        uses: xuanxu/paper-action@main
        with:
          repository_url: ${{ github.event.inputs.repository_url }}
          branch: ${{ github.event.inputs.branch }}
          issue_id: ${{ github.event.inputs.issue_id }}
          journal: test_journal
      - name: Test Python
        uses: xuanxu/test-python-action@main
        with:
          pdf_path: ${{ steps.generate-files.outputs.pdf_path}}
